export const newsletterCopy = {
  en: {
    title: "A new article, straight to your inbox",
    description: "Get an email when I publish something new.",
    email: "Email address", consent: "I would like to receive new articles by email. I can unsubscribe at any time.",
    privacy: "Privacy policy", submit: "Subscribe", busy: "Please wait…",
    success: "Check your inbox for a confirmation link. If you are already subscribed, you’re all set.",
    invalid: "Please enter a valid email address and agree to receive article updates.",
    unavailable: "Newsletter signup is temporarily unavailable. Please try again later.",
    rateLimit: "Too many requests. Please try again in an hour.",
    confirmTitle: "Confirm your subscription", confirm: "Confirm subscription",
    confirmDescription: "Confirm that you want to receive an email when a new article is published.",
    unsubscribeTitle: "Unsubscribe from article updates", unsubscribe: "Unsubscribe",
    unsubscribeDescription: "Select unsubscribe to stop receiving new article emails.",
    confirmed: "You’re subscribed. You’ll receive an email when a new article is published.",
    unsubscribed: "You’re unsubscribed and will no longer receive article updates.",
    expired: "This link is invalid, expired, or already used. You can sign up again below.",
    manageError: "We couldn’t update your subscription. Please try again.",
    back: "Back to the website",
    privacyTitle: "Article newsletter",
    privacyBody: "If you subscribe, we store your email address, chosen language, and signup and confirmation dates to send notifications about new articles through our configured email provider. Delivery starts only after you confirm your email. Each notification contains an unsubscribe link. Unconfirmed signups expire after 24 hours; unsubscribed records are deleted after 30 days. At signup, or confirmation if the location is missing, our IP geolocation provider receives your IP address to estimate your city, region, and country. We store the approximate location and coordinates to display subscriber distribution; we do not store your raw IP address in your subscriber record. A temporary hashed network identifier is used to limit signup abuse and expires after two hours.",
  },
  de: {
    title: "Neue Artikel direkt in dein Postfach",
    description: "Erhalte eine E-Mail, wenn ich einen neuen Artikel veröffentliche.",
    email: "E-Mail-Adresse", consent: "Ich möchte neue Artikel per E-Mail erhalten. Ich kann mich jederzeit abmelden.",
    privacy: "Datenschutzerklärung", submit: "Anmelden", busy: "Bitte warten…",
    success: "Schau in dein Postfach und bestätige deine Anmeldung über den Link. Wenn du bereits angemeldet bist, musst du nichts weiter tun.",
    invalid: "Bitte gib eine gültige E-Mail-Adresse ein und stimme dem Empfang neuer Artikel zu.",
    unavailable: "Die Anmeldung ist vorübergehend nicht verfügbar. Bitte versuche es später erneut.",
    rateLimit: "Zu viele Anfragen. Bitte versuche es in einer Stunde erneut.",
    confirmTitle: "Anmeldung bestätigen", confirm: "Anmeldung bestätigen",
    confirmDescription: "Bestätige, dass du bei neuen Artikeln per E-Mail informiert werden möchtest.",
    unsubscribeTitle: "Artikel-Newsletter abbestellen", unsubscribe: "Abmelden",
    unsubscribeDescription: "Klicke auf Abmelden, um keine E-Mails zu neuen Artikeln mehr zu erhalten.",
    confirmed: "Du bist angemeldet. Bei neuen Artikeln erhältst du eine E-Mail.",
    unsubscribed: "Du bist abgemeldet und erhältst keine weiteren Artikel-Benachrichtigungen.",
    expired: "Dieser Link ist ungültig, abgelaufen oder bereits verwendet. Du kannst dich unten erneut anmelden.",
    manageError: "Deine Anmeldung konnte nicht aktualisiert werden. Bitte versuche es erneut.",
    back: "Zurück zur Website",
    privacyTitle: "Artikel-Newsletter",
    privacyBody: "Wenn du dich anmeldest, speichern wir deine E-Mail-Adresse, gewählte Sprache sowie den Zeitpunkt der Anmeldung und Bestätigung, um dich über unseren konfigurierten E-Mail-Anbieter über neue Artikel zu informieren. Der Versand beginnt erst nach Bestätigung deiner E-Mail-Adresse. Jede Benachrichtigung enthält einen Abmeldelink. Unbestätigte Anmeldungen verfallen nach 24 Stunden; abgemeldete Datensätze werden nach 30 Tagen gelöscht. Bei der Anmeldung oder bei fehlendem Standort bei der Bestätigung erhält unser IP-Geolokalisierungsanbieter deine IP-Adresse, um Stadt, Region und Land näherungsweise zu bestimmen. Wir speichern den ungefähren Standort und die Koordinaten zur Darstellung der Abonnentenverteilung; deine vollständige IP-Adresse wird nicht im Abonnentendatensatz gespeichert. Eine temporäre gehashte Netzwerkkennung begrenzt missbräuchliche Anmeldungen und verfällt nach zwei Stunden.",
  },
};
